21 created registration page
bagotville/game pull request #10
Opened 2022-03-04 06:22 UTC by iliya132

also created login page, logout page, reworked console strategy to function

2022-03-05 12:07 UTC, sergey-chumakv commented on package.json
> -    "optimize-css-assets-webpack-plugin": "6.0.1",
Почему решил удалить?

2022-03-05 12:07 UTC, sergey-chumakv commented on src/pages/auth/Login/Login.constants.ts
> +export const defaultLoginProps: IConsoleStrategyProps<StringOnlyValues> = {
Мне кажется стоит капсом назвать константы

2022-03-05 12:07 UTC, sergey-chumakv commented on src/pages/auth/Login/Login.tsx
> +    console.log('login', result);
console.log остался

2022-03-05 12:07 UTC, sergey-chumakv commented on src/pages/auth/register/Register.tsx
> +interface RegisterProps extends StringOnlyValues {
Я вроде уже создавал такой интерфейс

2022-03-05 12:07 UTC, sergey-chumakv commented on src/pages/auth/register/Register.constants.ts
> +export const defaultRegisterProps: IConsoleStrategyProps<StringOnlyValues> = {
Да и тут можно капсом назвать

2022-03-05 12:07 UTC, sergey-chumakv commented on src/pages/auth/register/Register.tsx
> +/* eslint-disable spaced-comment */
это зачем?

2022-03-05 12:07 UTC, sergey-chumakv commented on src/pages/auth/Login/Login.tsx
> +/* eslint-disable spaced-comment */
и тут зачем?)

2022-03-05 14:25 UTC, iliya132 commented on package.json
> -    "optimize-css-assets-webpack-plugin": "6.0.1",
Ломает сборку

2022-03-05 14:27 UTC, sergey-chumakv commented on package.json
> -    "optimize-css-assets-webpack-plugin": "6.0.1",
Ну это довольно странно. У меня и dev и prod собираются нормально

2022-03-06 12:20 UTC, ashugaev requested changes

2022-03-06 12:20 UTC, ashugaev commented on package.json
> -    "optimize-css-assets-webpack-plugin": "6.0.1",
Да, проверь это еще раз. Возможно у тебя локально какие-то проблемы были. Это популярный плагин, там не должно быть сложностей с ним.

2022-03-06 12:20 UTC, ashugaev commented on src/pages/auth/Login/Login.tsx
> +/* eslint-disable spaced-comment */
Если выключать таким образом, то от этих правил нет смысла. Нужно постараться либо настроить линтер не так жестко, либо точечно ставить игноры, что бы не забывать удалять их вместе с кодом если что.

2022-03-06 12:20 UTC, ashugaev commented on src/components/ConsoleStrategy/ConsoleStrategy.style.scss
> +  color: red;
Лучше брать константы, что бы контролировать лучше цвета

2022-03-06 12:20 UTC, ashugaev commented on src/components/ConsoleStrategy/ConsoleStrategy.tsx
> +    tempInputValue = input.currentTarget.value;
Зачем tempInputValue?
Тут без стейта оно хранится, это может привести к не предсказуемому поведению. Значение может теряться при перерендере. Сейчас его изменение по сути ничего не триггерит.

2022-03-06 12:20 UTC, ashugaev commented on src/pages/auth/Login/Login.tsx
> +  const loginProps = defaultLoginProps;
Давай сразу определим тут интерфейс LoginPage и примем сверху пропсы. Что бы это было потом проще подключать.

Не уверен, что тут удобно юзать для дефолтных пропсов общий объект.

Коллбеки можно не объявлять. Просто в месте вызова делать проверку
`onSuccessHookHandler?.()` - это норм работает. Но вкусовщина. Можно и пустые ф-ции объявлять.

Я предлагаю вынести messages в константу и дефолтные через дестрктуризацию как обычно присваивать.

```
export function LoginPag(props: LoginPangeProps) {
const {
  messages: LOGIN_MESSAGES
} = props:
...
```

2022-03-06 12:20 UTC, ashugaev commented on src/pages/auth/register/Register.tsx
> +  const registerProps = defaultRegisterProps;
Тут то же самое с пропсами

2022-03-06 12:20 UTC, ashugaev commented on src/pages/auth/register/Register.tsx
> +  function validate(result: ISignupForm) {
Кажется эту ф-ция можно вынести наружу компонента. Что бы не пересоздавать её на перерендерах.

2022-03-06 12:20 UTC, ashugaev commented on src/pages/auth/register/Register.tsx
> +interface RegisterProps extends StringOnlyValues {
Интерфейсы вроде кладем же в отдельный файлик `*.interfaces.ts`

2022-03-06 12:20 UTC, ashugaev commented on src/utils/objectUtils.ts
> +export function computeHashForMessage<T extends StringOnlyValues>(
Это точно нужно?) 
Я понял, что это для `key`, но там будут проблемы, если отказаться от хэшей?

2022-03-06 18:21 UTC, iliya132 commented on src/pages/auth/Login/Login.tsx
> +/* eslint-disable spaced-comment */
Это я добавил что бы во время разработки не мешало. Сюда попало по невнимательности. Удалил конечно же. Спасибо.

2022-03-06 18:26 UTC, iliya132 commented on src/components/ConsoleStrategy/ConsoleStrategy.tsx
> +    tempInputValue = input.currentTarget.value;
Оно хранится без стейта с тем умыслом что его изменение не должно триггерить рендер.
Это значение, которое вводит пользователь в input. Т.е. пользователь нажал на кнопку - мы синканули значение из инпута. Зачем? Что бы избежать связности на ДОМ. Можно конечно получать значение из инпута когда надо, но кажется так дешевле.

2022-03-06 18:40 UTC, iliya132 commented on src/utils/objectUtils.ts
> +export function computeHashForMessage<T extends StringOnlyValues>(
Удалил хэши

2022-03-06 18:45 UTC, iliya132 commented on package.json
> -    "optimize-css-assets-webpack-plugin": "6.0.1",
Мы используем webpack 5. Этот плагин работает только с версией 4. Инфа об этом есть на страничке плагина. Вместо него с 5 вебпаком следует использовать [css-minimizer-webpack-plugin](https://github.com/webpack-contrib/css-minimizer-webpack-plugin)

2022-03-06 18:45 UTC, iliya132 commented on package.json
> -    "optimize-css-assets-webpack-plugin": "6.0.1",
Добавлю css-minimizer

2022-03-06 23:04 UTC, sergey-chumakv approved these changes

2022-03-07 15:31 UTC, ashugaev approved these changes

2022-03-07 15:31 UTC, merged