#26 add page profile
bagotville/game pull request #9
Opened 2022-02-21 23:23 UTC by sergey-chumakv

2022-02-22 03:33 UTC, iliya132 commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
минорное, лучше вроде разрешить выставлять это значение в правильное, типа newPassword, login итп

2022-02-22 04:04 UTC, iliya132 requested changes, later dismissed

2022-02-22 04:04 UTC, iliya132 commented on src/components/Main/Main.tsx
> +        <Route path={ROUTES.profile} element={<Profile />} />
У нас кажется роутинг в App.tsx ? Может не будем его размазывать по приложению?

2022-02-22 04:04 UTC, iliya132 commented on src/services/constants.ts
> +export const REG_EXP_VALIDATE_NAME = /^[A-ZА-Я][a-zа-я-]*$/;
минорное наверное ограничение на заглавную не принципиально все-таки. Можно самим ее сделать заглавной

2022-02-22 04:04 UTC, iliya132 commented on src/services/hooks/useValidate/useValidate.tsx
> +        if (value) {
тут наверное isInvalid должно быть. Вроде как всегда почти true будет

2022-02-22 04:04 UTC, iliya132 commented on src/services/hooks/useValidate/useValidate.tsx
> +      successMessage: 'Email is correct',
Почему то не используется

2022-02-22 04:04 UTC, iliya132 commented on src/services/hooks/useValidate/useValidate.tsx
> +      successMessage: 'First name is correct',
Валидация произойдет один раз в момент инициализации. По идее нужно проверять внутри setValue

2022-02-22 04:04 UTC, iliya132 commented on src/services/hooks/useValidate/useValidate.tsx
> +        value = /([^A-Za-zА-Яа-я-])/[Symbol.replace](value, '');
А чего тут magic string? Почему бы не использовать константы с regex?

2022-02-22 04:04 UTC, iliya132 commented on src/services/hooks/useValidate/useValidate.tsx
> +  }
Вообще было бы здорово написать универсальный метод который на вход принимает regexp и другие правила, наподобие isRequired, minLen, maxLen и делает всю работу. А то тут очень много повторяющегося кода. Просто для примера https://github.com/iliya132/middle.messenger.praktikum.yandex/blob/main/src/utils/inputValidator.ts

2022-02-22 04:04 UTC, iliya132 commented on src/pages/Profile/Profile.tsx
> +        />
повторяющийся код) Может вынесем в отдельную функцию? тогда тут станет заметно чище и не придется повторяться

2022-02-22 19:32 UTC, ashugaev commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
В идеале такие вещи делать через Enum как по мне. Что бы через него же их потом и прокидывать.

2022-02-22 19:32 UTC, ashugaev commented on src/components/Main/Main.scss
> +  & > div {
Тут очень неявное место. Лучше через класснейм вешать стили.

2022-02-22 19:32 UTC, ashugaev commented on src/pages/Profile/Profile.scss
> +  & > div {
то же самое с класснеймом

2022-02-22 19:32 UTC, ashugaev commented on src/pages/Profile/Profile.scss
> +  & > svg {
В идеале конечно иконку конфигурировать пропсом. 
Для этого нужно будет константы из scss экспортить в js

2022-02-22 19:32 UTC, ashugaev commented on src/pages/Profile/Profile.scss
> +  @include inputs-row;
О, круто. Миксины тут прям кстати

2022-02-22 19:32 UTC, ashugaev commented on src/styles/scroll.scss
> +  &::-webkit-scrollbar-button {
Не уверен что это под звездой должно вешаться.
Судя по всему должно без обертки работать

<img width="816" alt="Снимок экрана 2022-02-22 в 22 14 58" src="https://user-images.githubusercontent.com/36035849/155202706-ef58348e-dd02-408c-b707-2e4e8f4d61cb.png">

2022-02-22 19:32 UTC, ashugaev commented on src/styles/root.scss
> +  & > div:first-child {
тут не получится избавиться тоже от div? Просто по стилям вообще не понятно куда они применятся.

2022-02-22 19:32 UTC, ashugaev commented on src/services/index.ts
> +export { REG_EXP_VALIDATE_EMAIL } from './constants';
Тут кажется много строк можно заменить на `export * from './constants'`

2022-02-22 19:32 UTC, ashugaev commented on src/services/hooks/useValidate/useValidate.tsx
> +import { useState } from 'react';
А почему не стал брать готовый инструмент для валидации?

2022-02-24 15:39 UTC, sergey-chumakv commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
Это значение для инпута. У него нет таких type своих. А кроме этих нам особо и не нужно больше

2022-02-24 15:39 UTC, sergey-chumakv commented on src/components/Main/Main.tsx
> +        <Route path={ROUTES.profile} element={<Profile />} />
В мастере роутинг теперь в майн весь

2022-02-24 15:39 UTC, sergey-chumakv commented on src/services/constants.ts
> +export const REG_EXP_VALIDATE_NAME = /^[A-ZА-Я][a-zа-я-]*$/;
Ну я взял из прошлого модуля регулярки на валидацию. Там в требованиях была. Ну а апишка одна и та же и я подумал оставить как было. Я сделал ее сам заглавной при вводе. Ну лишней она тут не будет)

2022-02-24 15:39 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidate.tsx
> +      successMessage: 'Email is correct',
![image](https://user-images.githubusercontent.com/87362741/155086415-2e42b747-c600-4afa-8325-56c088769ec0.png)

2022-02-24 15:39 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidate.tsx
> +      successMessage: 'Email is correct',
тут не оч понял. Почему не используется?

2022-02-24 15:39 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidate.tsx
> +        if (value) {
isInvalid проверяется отдельным флагом

2022-02-24 15:39 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidate.tsx
> +      successMessage: 'First name is correct',
Нет. При вызове хука создается окружение где value это состояние. Оно как бы запоминается а при каждом изменении хук отдает нам новый объект. Ну в общем все работает корректно)

2022-02-24 15:39 UTC, sergey-chumakv commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
Ну по сути это базовые значения базового атрибута type у input я просто описал только 3 за ненадобностью остальных. Просто чтоб проще было в компонет инпут их указывать. Поэтмоу не вижу смысла выносить их в enum

2022-02-24 15:39 UTC, sergey-chumakv commented on src/components/Main/Main.scss
> +  & > div {
+

2022-02-24 15:39 UTC, sergey-chumakv commented on src/pages/Profile/Profile.scss
> +  & > svg {
заведу задачу на рефактор svg

2022-02-24 15:39 UTC, sergey-chumakv commented on src/services/index.ts
> +export { REG_EXP_VALIDATE_EMAIL } from './constants';
+

2022-02-24 15:39 UTC, sergey-chumakv commented on src/styles/scroll.scss
> +  &::-webkit-scrollbar-button {
да и правда

2022-02-24 15:39 UTC, sergey-chumakv commented on src/styles/root.scss
> +  & > div:first-child {
Это рутовый див. Через #root почему то не хочет подтягивать стили

2022-02-24 20:06 UTC, GalenMad commented on src/pages/Profile/Profile.scss
> +  & > div {
Согласен, тут очень неочевидно будет

2022-02-24 20:10 UTC, GalenMad commented on src/services/constants.ts
> +export const REG_EXP_VALIDATE_NAME = /^[A-ZА-Я][a-zа-я-]*$/;
Мне кажется, что нужно либо говорить юзеру делать заглавной, либо использовать маску с автоматическим преобразованием. Иначе юзеру будет неочевидно.

2022-02-24 20:11 UTC, GalenMad commented on src/services/hooks/useValidate/useValidate.tsx
> +import { useState } from 'react';
Обсудили сегодня на созвоне

2022-02-25 09:37 UTC, ashugaev commented on src/components/Input/Input.tsx
>      isInvalid = false,
Зачем кстати два флага isValid и isInvalid?
Они же всегда будут содержать противоположный boolean?

2022-02-25 09:37 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
Что за isDirty не пойму?

2022-02-25 09:37 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +    update: () => {
Зачем два метода для обновления value?

2022-02-25 09:37 UTC, ashugaev commented on src/components/Button/Button.scss
> +.confirm {
Разные вариации кнопки лучше делать под модификаторами. Как-то так

```
.button {
  ....

  &_cancel {
        ....
  }
   
  &_confirm {
       ...
  }
}
```

Нe будут дублироваться какие-то стили и будет понятна иерархия.

Можно удлиннить название и сделать прям по BEM

`.button_variant_cancel` и т.д.

2022-02-25 09:37 UTC, ashugaev commented on src/components/Button/Button.tsx
> +      [ <span className={styles[type]}>{name}</span> ]
А зачем span? 
И массив?

2022-02-25 09:37 UTC, ashugaev commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
Это просто удобнее, что будут отдельно лежать все варианты значений для поля. 

Тем более дальше будут другие кейсы, где значения будут свои (может темы, может какие-то другие внешние изменения компонентов) и возможно вариантов будет много. 

Лучше сразу писать консистентно. Либо потом будет часть написано одним образом, часть другим.

2022-02-25 09:38 UTC, ashugaev commented on src/services/hooks/useValidate/useValidate.tsx
> +        if (value) {
value.length может быть?

2022-02-25 09:42 UTC, ashugaev requested changes

2022-02-25 09:42 UTC, ashugaev commented on src/services/validatior/validator.types.ts
> +export interface IValidationErrors {
Почему в виде объекта возвращаешь? Кажется лучше работать с массивом для отображения ошибок

2022-02-25 09:57 UTC, sergey-chumakv commented on src/components/Input/Input.tsx
>      isInvalid = false,
Ну по сути да. Просто для удобства. Что бы не использовать отрицания

2022-02-25 09:59 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
isDirty означает что в форму или инпут что то вводилось. То есть если нужно сделать валидацию только после изменения какого то инпута или значения.

2022-02-25 10:03 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidateControl.ts
> +    update: () => {
ну один который работает в хуке одного контрола. А возвращаемый вызывается в хуке формы что бы состояния всех инпутов формы были актуальными. То есть если например создать валидатор на одинаковые пароли и он отрабатывает при вводе в инпут password repeat а после изменить input с new password чтобы password repeat не оставался валидным.

2022-02-25 10:05 UTC, sergey-chumakv commented on src/components/Button/Button.scss
> +.confirm {
Ну тут возможно да. Не хотел делать большую вложенность наверно

2022-02-25 10:06 UTC, sergey-chumakv commented on src/components/Button/Button.tsx
> +      [ <span className={styles[type]}>{name}</span> ]
Это не массив) Это кнопка так выглядит 
![image](https://user-images.githubusercontent.com/87362741/155696145-af34512f-dd4a-4af8-bafd-716770575b1e.png)
спан что бы скобки не меняли цвет и не подчеркивались

2022-02-25 10:07 UTC, sergey-chumakv commented on src/services/validatior/validator.types.ts
> +export interface IValidationErrors {
Потому что если несколько валидаторов одновременно подсвечивают ошибки удобней получать их по ключу. И выводить любую из них тогда когда это будет нужно и где нужно. С массивом так не получится

2022-02-25 10:11 UTC, sergey-chumakv commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
Ну если изменить тему у нас же не поменяется тип инпута с email на password) И мы не создаем же enum для типов Input или button. У нас с вероятностью 99% не будет никакого типа кроме этих 3. Мне не сложно сделать я могу) но смысла в этом не вижу

2022-02-25 11:55 UTC, ashugaev commented on src/services/validatior/validator.ts
> +export class Validator {
Это уже выглядит гораздо лучше чем предыдущее решение

2022-02-25 11:55 UTC, ashugaev commented on src/pages/Profile/Profile.tsx
> +function getErrorMessage(
Выглядит так что ото всей ф-ции можно избавиться, если ошибки отдавать в виде массива и брать 0 индекс просто.

2022-02-25 11:55 UTC, ashugaev commented on src/pages/Profile/Profile.types.ts
> +export const PROFILE_INPUTS_DATA: IProfileInput[] = [
Почему это в типах?

2022-02-25 11:55 UTC, ashugaev commented on src/pages/Profile/Profile.types.ts
> +export const PROFILE_INPUTS_PASSWORD: IProfileInput[] = [
Это тоже надо бы вынести в константы

2022-02-25 11:55 UTC, ashugaev commented on src/pages/Profile/Profile.types.ts
> +    className: 'new-pass',
Класснейм надо взять через импорт styles

2022-02-25 11:58 UTC, ashugaev commented on src/components/Input/Input.tsx
>      isInvalid = false,
Нет особо смысла нагромождать интерфейс для таких кейсов. Лучше внутри компонента если нужно объявить `isInvalid = !isValid` если нужно. Давай это грохнем, что бы дальше не завязываться на этот проп.

2022-02-25 12:04 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
Не очевидно конечно сходу. Такие вещи лучше в интерфейсе документировать.

2022-02-25 12:05 UTC, ashugaev commented on src/components/Input/Input.tsx
>      isInvalid = false,
Либо техдолг таску оставь, если сейчас не хочешь заниматься этим

2022-02-25 12:07 UTC, ashugaev commented on src/components/Input/Input.types.ts
> +  autoComplete?: 'on' | 'off';
Ну ок, решай сам как тут поступить

2022-02-25 12:10 UTC, sergey-chumakv commented on src/components/Input/Input.tsx
>      isInvalid = false,
А я перепутал немного. В инпуте isInvalid и isValid нужны для стилей валидации. Просто изначально и тот и другой в false. И инпут как бы серый. А потом получается меняется флаг какой то и инпут становится зеленый или красный. Если сделать один флаг тру фолс то получится что инпут изначально будет либо красный либо зеленый

2022-02-25 12:11 UTC, sergey-chumakv commented on src/components/Input/Input.tsx
>      isInvalid = false,
возможно решение не самое лучшее. Но все же решал пока так оставить

2022-02-25 12:12 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +    update: () => {
🤔 А что помешает другому разработчику, когда он будет писать форму использовать неправильный метод?

2022-02-25 12:14 UTC, sergey-chumakv commented on src/pages/Profile/Profile.types.ts
> +    className: 'new-pass',
Не очень понял

2022-02-25 12:19 UTC, ashugaev commented on src/services/validatior/validator.types.ts
> +export interface IValidationErrors {
Обычно нужно достать либо первое сообщение об ошибке. Их порядок можно определять валидаторами. Это избавит тебя от той ф-ции, что ты писал для вытаскивания по ключу))

2022-02-25 12:20 UTC, sergey-chumakv commented on src/pages/Profile/Profile.tsx
> +function getErrorMessage(
Ну тут ошибки в определенном порядке расположены. Что бы например ошибка регулярки на логин не перекрывала ошибку минимальной длинны. Получается как бы видно и понятно какую имеенно ошибку ты берешь. А в массиве не очень очевидно в каком порядке у тебя будут подсвечиватся ошибки. И сколько их в массиве.

2022-02-25 12:22 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidateControl.ts
> +    update: () => {
Всмысле? Какой метод неправильный?) update метод один возвращаемый который вызывает просто функцию update обьявленую внутри хука чтобы код не дублировать

2022-02-25 12:23 UTC, ashugaev commented on src/components/Button/Button.scss
> +.confirm {
В данном случае это обоснованно. Это не каскад по сути, а синтаксис scss для конструирования названий

Каким-то образом лучше объединять такого рода классы, что бы они не были разбросаны по файлу беспорядочно. В крайнем случаем комментом, который будет говорить, что ниже идут вариации кнопок.

2022-02-25 12:24 UTC, sergey-chumakv commented on src/services/validatior/validator.types.ts
> +export interface IValidationErrors {
Ну по сути да. Если определять порядок валидаторами. Но вот если другой разработчик будет использовать этот хук далеко не сразу можно догадается что вывод ошибок инпута определяется именно порядком передаваемых валидаторов. Как по мне лучше больше но проще и очевидней)

2022-02-25 12:24 UTC, sergey-chumakv commented on src/pages/Profile/Profile.types.ts
> +export const PROFILE_INPUTS_DATA: IProfileInput[] = [
тут согласен перенесу в константы

2022-02-25 12:25 UTC, sergey-chumakv commented on src/pages/Profile/Profile.types.ts
> +export const PROFILE_INPUTS_PASSWORD: IProfileInput[] = [
+

2022-02-25 12:31 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
Как документировать?

2022-02-25 14:56 UTC, ashugaev commented on src/pages/Profile/Profile.types.ts
> +    className: 'new-pass',
```
import styles from './profile.scss

className: styles['new-pass'],
```

2022-02-25 15:00 UTC, ashugaev commented on src/pages/Profile/Profile.tsx
> +function getErrorMessage(
Массив гарантирует порядок. Управлять порядком можно через порядок валидаторов, которые у тебя тоже являются массивом.

Минус такой реализации в том, что с добавлением валидатора нужно добавить еще условие в этой ф-ции. 

Не забывай про то, что твой код будет поддерживаться.

2022-02-25 15:07 UTC, ashugaev commented on src/pages/Profile/Profile.tsx
> +function getErrorMessage(
Можешь резолвить тред по своему усмотрению, нет смысла его растягивать.

2022-02-25 15:15 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
```
export interface IControlInfo {
  value: string;
  isValid: boolean;
  isInvalid: boolean;
  /**
   *. Можно тут в jsdoc
   **/
  isDirty: boolean;
  errors: IValidationErrors;
  setValue: (value: string) => void;
  update: () => void;
}
```

2022-02-25 15:16 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
Можно подписать над объявленным стейтом. Либо еще вариант более говорящее название делать.

2022-02-25 15:17 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +      setIsDirty(true);
Но в интерфейсе оптимально, потому что на него смотрят, когда юзают ф-цию и ide будет норм работать с этим

2022-02-25 15:18 UTC, ashugaev commented on src/services/hooks/useValidate/useValidateControl.ts
> +    update: () => {
Как я понял тут можно вызвать update вместо setValue

<img width="626" alt="Снимок экрана 2022-02-25 в 18 18 12" src="https://user-images.githubusercontent.com/36035849/155740246-5fd06279-7f86-434e-8b03-ce0d8f72b2af.png">

2022-02-25 23:50 UTC, sergey-chumakv commented on src/services/hooks/useValidate/useValidateControl.ts
> +    update: () => {
Ну по сути можно да. Но он просто акуализирует состояние контрола. Как бы хуже он не сделает да и название говорит о том что он просто обновит состояние

2022-02-25 23:57 UTC, sergey-chumakv commented on src/pages/Profile/Profile.tsx
> +function getErrorMessage(
Ну по сути это тут нужно делать функцию просто по тому что у меня на странице 9 инпутов с кучей ошибок. Так можно передать на прямую. Да и запись вида errors.required || errors.minLength выглядит более очевидной чем errors[0]. Ну опять же мне не принципиально. Пусть остальные участники команды решат как лучше тогда)

2022-02-26 08:11 UTC, ashugaev approved these changes

2022-02-26 13:06 UTC, GalenMad approved these changes

2022-02-26 15:37 UTC, merged